# Generated by Django 5.1.4 on 2025-01-04 17:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="analyses",
            old_name="analyses",
            new_name="summary",
        ),
    ]
