# Generated by Django 5.1.4 on 2025-01-05 02:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_rename_analyses_analyses_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="analyses",
            name="document_name",
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
