# Generated by Django 5.1.4 on 2025-01-05 02:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_analyses_document_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="analyses",
            old_name="key_points",
            new_name="analyses",
        ),
        migrations.RemoveField(
            model_name="analyses",
            name="legal_issues",
        ),
        migrations.RemoveField(
            model_name="analyses",
            name="relevant_cases",
        ),
        migrations.RemoveField(
            model_name="analyses",
            name="summary",
        ),
    ]
